### PR TITLE
Add option adding mechanics

### PR DESCRIPTION
**Pull request by tensojka**
This proposals adds option adding to the Cairo 1 governance contract.

More options will be added in the next commit in this PR, please review the option-adding code itself. Old option adding code: https://github.com/CarmineOptions/carmine-protocol/blob/master/contracts/governance/orchestration.cairo

### CODE REVIEW

**Comment by tensojka** [comment]
Also uppped default voting time to 1000

**Comment by tensojka** [comment]
Tested:

- deployed on testnet governance contract 0x5b54870844c456ae99bfbaf02c40030c0e0ec59a55f8911168750841649027b in tx 0x502471e5d42db9f73adf34b346b2b2a5475b48685dcad06790215a5bf61909c (minted tokens to shared core team testnet admin too)
- amm then is 0x01ff7b5983e016490b7f02844bbf3876ec86ad0cc59e98808982c61084e5a524
- declared 0x56bdfca481046a4e172411875281fbb312e31f3d66db3e11dff54c3e04b0416 – Cairo 1 class hash with this option adding code, with constants such as ETH_addr adjusted for testnet.
- proposed, passed
- applied proposal
- invoke add_2206_options()
- try to invoke again, fails
- when I try to trade, it fails on Empiric oracle
- declare new AMM on testnet with Empiric addr fixed
- submit proposal 1, class hash 0x583d4e3dcb85a2376098f6b4b26cebe406a2356da0d4004bfd20432490c8d74, upgrading AMM (type 0)
- vote against with one wallet, vote for with one bigger wallet, pass proposal.
- Error message: Received price which is over an hour old

gn

**Comment by tensojka** [comment]
- declare 0x34c8a486ca2014f54fc9e7320e169f37635a25ccfab7a7b319377556c4b1eaa AMM with fixed empiric testnet price... We really need a preprocessing step
- pass as prop 3
- tx 0x19e8f4bd47164b68947587d4f37d0293d65ba40819f3c7e2e0d30986e647d67 successfully buys newly added option.

I think we're good to go

**Comment by Chepelau** [comment]
Looks good to me

**Comment by StarkFishinator** [comment]
I am only able to compare the `add_option` and `deploy_via_proxy` function, the other (`add_2906_options`, `add_2206_options`, `add_2206_2906_options`) are not present in the orchestration.cairo file

**Comment by tensojka** [comment]
> I am only able to compare the `add_option` and `deploy_via_proxy` function, the other (`add_2906_options`, `add_2206_options`, `add_2206_2906_options`) are not present in the orchestration.cairo file

They are present in upgrades.cairo in the old Cairo 0 version. I found this to be a bit of a mess and refactored everything option-related into options.cairo. I also added the FutureOption struct so add_option isn't called directly – this will then allow us to more easily add sanity checks or generate FutureOption structs later. (They aren't being generated currently because there's no support for string concatenation, I will have to add that to alexandria.)

**Comment by tensojka** [comment]
Declared as contract class hash 0x5af04d58b128176d39ffaa4017dbece49cd992b34995f41e54ecf1da52e9a88 in tx 0x15099863cb3220efb367d8ee35198622f4e7798c8b740fa51ee1c625669ca42

**Review by Nerrolol — APPROVED** [review]
everything looks good to me

**Pull request merged**
